# Generated by Django 5.2 on 2026-08-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (рус.)')),
                ('title_ky', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (кырг.)')),
                ('body_ru', models.TextField(verbose_name='Текст (рус.)')),
                ('body_ky', models.TextField(blank=True, verbose_name='Текст (кырг.)')),
                ('audience', models.CharField(choices=[('all', 'Всем арендаторам'), ('building', 'Арендаторам корпуса'), ('debtors', 'Только должникам')], default='all', max_length=10, verbose_name='Получатели')),
                ('publish_from', models.DateTimeField(blank=True, null=True, verbose_name='Публикация с')),
                ('publish_to', models.DateTimeField(blank=True, null=True, verbose_name='Публикация до')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Разослано')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.building', verbose_name='Корпус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(choices=[('charge_created', 'Новое начисление (FR-NT-02)'), ('reminder_10', 'Напоминание за 10 дней'), ('reminder_5', 'Напоминание за 5 дней'), ('reminder_3', 'Напоминание за 3 дня'), ('reminder_0', 'Напоминание в день срока'), ('claim_confirmed', 'Заявка подтверждена, долг погашен'), ('claim_confirmed_partial', 'Заявка подтверждена, остался долг'), ('claim_rejected', 'Заявка отклонена (FR-NT-04)'), ('overdue', 'Просрочка оплаты (FR-NT-05)'), ('announcement', 'Объявление администрации')], max_length=40, verbose_name='Код события')),
                ('lang', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский')], max_length=2, verbose_name='Язык')),
                ('title_template', models.CharField(max_length=255, verbose_name='Шаблон заголовка')),
                ('body_template', models.TextField(verbose_name='Шаблон текста')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'constraints': [models.UniqueConstraint(fields=('code', 'lang'), name='uniq_template_code_lang')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=40, verbose_name='Код события')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Полезная нагрузка')),
                ('channel', models.CharField(default='push', max_length=10, verbose_name='Канал')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Не доставлено')], default='queued', max_length=10, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка доставки')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток отправки')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__b302ab_idx'), models.Index(fields=['status'], name='notificatio_status_d92267_idx'), models.Index(fields=['tenant', 'code', 'created_at'], name='notificatio_tenant__2f1844_idx')],
            },
        ),
    ]
