# Generated by Django 5.2 on 2026-08-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ (SHA-256)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='Устройство')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Токен арендатора',
                'verbose_name_plural': 'Токены арендаторов',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('push_token', models.CharField(blank=True, max_length=512, verbose_name='Push-токен')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, verbose_name='Платформа')),
                ('app_version', models.CharField(blank=True, max_length=20, verbose_name='Версия приложения')),
                ('locale', models.CharField(blank=True, max_length=10, verbose_name='Локаль устройства')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='TenantLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_attempted', models.CharField(max_length=20, verbose_name='Введённый ИНН')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent / устройство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Вход арендатора',
                'verbose_name_plural': 'Журнал входов арендаторов',
                'indexes': [models.Index(fields=['ip', 'created_at'], name='accounts_te_ip_10bda8_idx'), models.Index(fields=['inn_attempted', 'created_at'], name='accounts_te_inn_att_0ebdf5_idx')],
            },
        ),
    ]
