# Generated by Django 5.2 on 2026-08-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('success', models.BooleanField(verbose_name='Успешно')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Вход администратора',
                'verbose_name_plural': 'Журнал входов администраторов',
                'indexes': [models.Index(fields=['username', 'created_at'], name='accounts_ad_usernam_faef88_idx')],
            },
        ),
    ]
