# Generated by Django 5.2 on 2026-08-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код места')),
                ('spot_type', models.CharField(choices=[('container', 'Контейнер'), ('pavilion', 'Павильон'), ('counter', 'Прилавок'), ('boutique', 'Бутик'), ('other', 'Другое')], default='container', max_length=20, verbose_name='Тип')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь, м²')),
                ('status', models.CharField(choices=[('free', 'Свободно'), ('occupied', 'Занято'), ('repair', 'На ремонте')], default='free', max_length=10, verbose_name='Состояние')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spots/', verbose_name='Фотография')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='catalog.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Торговое место',
                'verbose_name_plural': 'Торговые места',
                'ordering': ['building__code', 'code'],
            },
        ),
    ]
