# Generated by Django 5.2 on 2026-08-14 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('inn', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ИНН')),
                ('passport_number', models.CharField(blank=True, max_length=30, verbose_name='Номер паспорта')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tenants/', verbose_name='Фотография')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('suspended', 'Приостановлен'), ('archived', 'Архивный')], default='active', max_length=10, verbose_name='Статус')),
                ('billing_day', models.PositiveSmallIntegerField(blank=True, help_text='Пусто — берётся общая настройка', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Дата начисления')),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, help_text='Пусто — берётся общая настройка', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Срок оплаты')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('ky', 'Кыргызский')], default='ru', max_length=2, verbose_name='Язык интерфейса')),
                ('announcements_enabled', models.BooleanField(default=True, verbose_name='Получает объявления')),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласие на обработку ПДн принято')),
                ('consent_version', models.CharField(blank=True, max_length=20, verbose_name='Версия текста согласия')),
                ('pin_hash', models.CharField(blank=True, help_text='Используется только при включённой настройке pin_login_enabled', max_length=128, verbose_name='PIN-код (хеш)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='tenant_docs/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Документ арендатора',
                'verbose_name_plural': 'Документы арендаторов',
            },
        ),
        migrations.CreateModel(
            name='TenantSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма аренды в месяц')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_spots', to='catalog.spot', verbose_name='Место')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_spots', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Место арендатора',
                'verbose_name_plural': 'Места арендаторов',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('spot',), name='uniq_active_tenant_per_spot'), models.CheckConstraint(condition=models.Q(('monthly_amount__gte', 0)), name='tenantspot_amount_gte_0')],
            },
        ),
    ]
