# Generated by Django 5.2 on 2026-08-14 11:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('run_date', models.DateField(verbose_name='Дата прогона')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Предварительный просмотр')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано начислений')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая сумма')),
                ('skipped', models.JSONField(default=list, verbose_name='Пропущено (причины)')),
                ('errors', models.JSONField(default=list, verbose_name='Ошибки')),
                ('started_by', models.ForeignKey(blank=True, help_text='Пусто — запуск по расписанию', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Прогон начислений',
                'verbose_name_plural': 'Прогоны начислений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='Год периода')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='Месяц периода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Оплачено')),
                ('charged_date', models.DateField(verbose_name='Дата начисления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Оплачено частично'), ('paid', 'Оплачено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], default='unpaid', max_length=10, verbose_name='Статус')),
                ('source', models.CharField(choices=[('auto', 'Автоматическое'), ('manual', 'Ручное'), ('initial', 'Долг на начало работы Системы'), ('adjustment', 'Корректировка долга (в плюс)')], default='auto', max_length=12, verbose_name='Происхождение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cancelled_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_charges', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='tenants.tenant', verbose_name='Арендатор')),
                ('tenant_spot', models.ForeignKey(blank=True, help_text='Пусто для разовых начислений и начальной задолженности', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='tenants.tenantspot', verbose_name='Место арендатора')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['due_date', 'id'],
                'indexes': [models.Index(fields=['tenant', 'status', 'due_date'], name='billing_cha_tenant__ec49c0_idx'), models.Index(fields=['period_year', 'period_month'], name='billing_cha_period__6f2b8c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'auto'), models.Q(('status', 'cancelled'), _negated=True)), fields=('tenant_spot', 'period_year', 'period_month'), name='uniq_auto_charge_per_spot_period'), models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('paid_amount__lte', models.F('amount'))), name='charge_paid_within_amount'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='charge_amount_gte_0'), models.CheckConstraint(condition=models.Q(('charged_date__lt', models.F('due_date'))), name='charge_charged_before_due')],
            },
        ),
    ]
