# Generated by Django 5.2 on 2026-08-14 11:15

import apps.core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('market_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование рынка')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты рынка')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR-код для оплаты')),
                ('payment_instruction_ru', models.TextField(blank=True, verbose_name='Инструкция по оплате (рус.)')),
                ('payment_instruction_ky', models.TextField(blank=True, verbose_name='Инструкция по оплате (кырг.)')),
                ('default_billing_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Дата начисления по умолчанию')),
                ('default_payment_day', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Срок оплаты по умолчанию')),
                ('reminder_days', models.JSONField(default=apps.core.models.default_reminder_days, verbose_name='Дни напоминаний до срока оплаты')),
                ('overdue_notice_days', models.JSONField(default=apps.core.models.default_overdue_notice_days, verbose_name='Дни уведомления о просрочке (после срока)')),
                ('reject_reasons', models.JSONField(default=apps.core.models.default_reject_reasons, verbose_name='Причины отклонения заявок')),
                ('pin_login_enabled', models.BooleanField(default=False, verbose_name='Вход по PIN-коду включён')),
                ('consent_version', models.CharField(default='1.0', max_length=20, verbose_name='Версия текста согласия на обработку ПДн')),
                ('min_app_version', models.CharField(blank=True, help_text='Отдаётся в GET /app/config', max_length=20, verbose_name='Минимальная версия приложения')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('admin', 'Администратор'), ('tenant', 'Арендатор'), ('system', 'Система')], default='admin', max_length=10, verbose_name='Тип субъекта')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Прежнее значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id', 'created_at'], name='sys_core_au_model_n_42e32b_idx')],
            },
        ),
    ]
