# Generated by Django 5.2 on 2026-08-14 11:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма (плюс или минус)')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('reversed', 'Отменена')], default='active', max_length=10, verbose_name='Статус')),
                ('advance_excess', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Для корректировки в минус, превысившей долг', max_digits=12, verbose_name='Излишек, зачисленный в аванс')),
                ('charge', models.OneToOneField(blank=True, help_text='Для корректировки в плюс', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='billing.charge', verbose_name='Начисление корректировки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Корректировка долга',
                'verbose_name_plural': 'Корректировки долга',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('declared_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Заявленная сумма')),
                ('receipt_image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name='Фотография чека')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('withdrawn', 'Отозвана')], default='pending', max_length=10, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Подана')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='Ключ идемпотентности')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='Устройство')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL, verbose_name='Кто обработал')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Заявка об оплате',
                'verbose_name_plural': 'Заявки об оплате',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('paid_at', models.DateTimeField(verbose_name='Дата платежа')),
                ('source', models.CharField(choices=[('claim', 'По заявке'), ('manual', 'Внесён администратором')], max_length=10, verbose_name='Происхождение')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('reversed', 'Отменён (сторно)')], default='active', max_length=10, verbose_name='Статус')),
                ('reversed_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кто внёс/подтвердил')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='tenants.tenant', verbose_name='Арендатор')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentclaim', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['paid_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenantBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Долг')),
                ('advance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Аванс')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Баланс арендатора',
                'verbose_name_plural': 'Балансы арендаторов',
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('kind', models.CharField(choices=[('payment', 'Платёж'), ('advance', 'Зачёт аванса'), ('adjustment', 'Корректировка долга')], max_length=12, verbose_name='Вид')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('reversed', 'Отменено')], default='active', max_length=10, verbose_name='Статус')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.debtadjustment', verbose_name='Корректировка')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.charge', verbose_name='Начисление')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment', verbose_name='Платёж')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_allocations', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
            ],
            options={
                'verbose_name': 'Распределение платежа',
                'verbose_name_plural': 'Распределения платежей',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='allocation_amount_gt_0')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentclaim',
            index=models.Index(fields=['status', 'submitted_at'], name='payments_pa_status_97f80f_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentclaim',
            constraint=models.CheckConstraint(condition=models.Q(('declared_amount__gte', 1)), name='claim_amount_gte_1'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'paid_at'], name='payments_pa_tenant__35304d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_0'),
        ),
    ]
